In [5]:
for i in range(4):
    for j in range(4):
        if i+j<=2:
            print(" ",end=" ")
        else:
            print("*",end=" ")
    print( )

      * 
    * * 
  * * * 
* * * * 


In [8]:
name=input("enter the name")
for i in range(len(name)):
    for j in range(0,i+1):
      print(name[i],end='')
    print()
      

enter the namevirat
v
ii
rrr
aaaa
ttttt


In [ ]:
rec={}
n=int(input("enter the number of students"))
i=1
while i<=n:
    name=input("enter the student name")
    marks=input("enter % marks of student")
    rec[name]=marks
    i+=1
    print("name of the student","\t","% of marks")
    for x in rec:
        print("\t",x,"\t\t",rec[x])

In [ ]:
rec={}
n=int(input("enter the number of students"))
i=1
while i<=n:
    name=input("enter the student name")
    marks=input("enter % marks of student")
    rec[name]=marks
    i+=1
    print("name of the student","\t","% of marks")
    for x in rec:
        print("\t",x,"\t\t",rec[x])

In [ ]:
5+5


In [1]:
rec={}
n=int(input("enter the number of students"))
i=1
while i<=n:
    name=input("enter the student name")
    marks=input("enter % marks of student")
    rec[name]=marks
    i+=1
    print("name of the student","\t","% of marks")
    for x in rec:
        print("\t",x,"\t\t",rec[x])

enter the number of students2
enter the student namepratyush
enter % marks of student99
name of the student 	 % of marks
	 pratyush 		 99
enter the student namerande
enter % marks of student43
name of the student 	 % of marks
	 pratyush 		 99
	 rande 		 43


In [2]:
d.clear()


NameError: name 'd' is not defined

In [6]:
d={1:'xyz',2:'abc'}


In [7]:
d


{1: 'xyz', 2: 'abc'}

In [8]:
d.clear()

In [9]:
d


{}

In [10]:
word=input("enter any word")
d={}
for x in word:
    d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occure",v,"times")

enter any wordheeeelllllllloooooooo
h occure 1 times
e occure 4 times
l occure 8 times
o occure 8 times


In [12]:
word=input("enter a string")
d={}
vowels={'a','e','i','o','u'}
for x in word:
    if x in vowels:
        d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occure",v,"times")

enter a stringhow are you
o occure 2 times
a occure 1 times
e occure 1 times
u occure 1 times


In [16]:
square={x:x*x for x in range(1,6)}
print(square)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [17]:
n=[1,2,3,4,5,5,5,5]
print(n.count(5))

4


In [18]:
n=[1,2,3,4,5]
n.insert(1,888)
print(n)

[1, 888, 2, 3, 4, 5]


In [23]:
n=[1,2,3,4,5]
o=[6,7,8,9]
n.extend(o)
print(n)


[1, 2, 3, 4, 5, 6, 7, 8, 9]


### remove


In [24]:
n=[1,2,3,4,5]
n.remove(3)
print(n)

[1, 2, 4, 5]


In [25]:
n=[1,2,3,4,5]
n.pop()

5

In [26]:
n=[1,2,3,4,5]
n.pop()
print(n)

[1, 2, 3, 4]


In [27]:
n=[1,2,3,4,5]
n.reverse()
print(n)

[5, 4, 3, 2, 1]


In [28]:
n=['pratyush','shobith','shreyan','reevan']
n.sort()
print(n)

['pratyush', 'reevan', 'shobith', 'shreyan']


In [29]:
n=['pratyush','shobith','shreyan','reevan',1,2,3,4]
n.sort()
print(n)

TypeError: '<' not supported between instances of 'int' and 'str'

In [30]:
n=['pratyush','shobith','shreyan','reevan']
n.sort(reverse=True)
print(n)

['shreyan', 'shobith', 'reevan', 'pratyush']


In [34]:
x=[10,20,30,40]
y=x.copy()
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [35]:
a=[10,20,30,40]
b=[40,50,60]
c=a+b
print(c)

[10, 20, 30, 40, 40, 50, 60]


In [36]:
a=[10,20,30,40]
y=a*3
print(y)

[10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40]


In [38]:
x=["MITE","Mangalore","NITK"]
y=["MITE","Mangalore","NITK"]
x==y
x!=y
z=["MITE","Mangalore","NITK"]
x==z


True

In [39]:
m=[10,20,30,40,[50,60,70,80]]
m[3]
m[4][1]
m.clear()
n=[1,2,3,4]
print(4 in n)

True


In [40]:
s=[2**x for x in range(1,6)]
print(s)

[2, 4, 8, 16, 32]


In [41]:
words=["MITE","Mysore","Pratyush"]
n=[w[0] for w in words]
print(n)

['M', 'M', 'P']


In [42]:
seq=[1,2,3,4,5]
lambda var: var*2
list(map(lambda var: var*2,seq))

[2, 4, 6, 8, 10]

In [43]:
seq=[1,2,3,4,5]
lambda var: var*2
list(map(lambda var: var*2,seq))
list(filter(lambda item:item%2==0,seq))

[2, 4]

In [44]:
import numpy as np

In [1]:
np


NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
np


<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [4]:
my_list=[1,2,3]
my_list
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(2)


array([0.09197903, 0.58374272])

In [17]:
np.random.rand(5,5)

array([[0.62331275, 0.55004563, 0.73914409, 0.94586434, 0.09813029],
       [0.37317817, 0.98369949, 0.32229219, 0.16512886, 0.18968813],
       [0.10811754, 0.73180727, 0.89201708, 0.18195561, 0.92093553],
       [0.87632993, 0.4519755 , 0.37525927, 0.65354575, 0.9378912 ],
       [0.12727137, 0.81937703, 0.45602739, 0.21646807, 0.51484279]])

In [19]:
np.random.randn(5,5)

array([[-0.55092143,  0.67011153, -1.07134611, -0.84541803, -1.74338194],
       [ 0.63412099,  0.87291944, -1.53869611,  0.06783322,  2.0685979 ],
       [-0.68477279, -0.47670392,  0.39219046,  0.7223978 ,  1.75093794],
       [-1.33424473, -0.03222272,  0.76598814,  0.44067962,  0.05234347],
       [-0.9321612 , -0.58454105, -0.54427537, -0.73364454, -0.03292014]])

In [20]:
np.random.randint(1,100,10)

array([75, 31,  5,  7, 81, 60, 68, 68, 99, 92])

In [22]:
arr=np.arange(25)

In [23]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr.max()

24

In [26]:
arr.argmax()

24

In [27]:
arr.argmin()

0

In [28]:
arr.reshape(1,25).shape

(1, 25)

In [29]:
arr.dtype

dtype('int32')

In [30]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [32]:
arr.reshape(25,1).shape

(25, 1)

In [33]:
arr.dtype

dtype('int32')

In [35]:
arr=np.arange(0,10)

In [36]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [39]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
arr/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [41]:
1/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [42]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [43]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [44]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [45]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [46]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [47]:
arr=np.arange(0,11)

In [48]:
arr
arr[8]
arr[1:5]
arr[0:5]
arr[0:5]=100

In [49]:
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [50]:
 arr>4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [51]:
arr[arr>4]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [2]:
np.zeros(12)

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
my_list=[5,5,5,5,5,5,5,5,5,5]
my_list
np.array(my_list)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])